SUBDIRS=bit-range bit-range-ocaml cell_map cell-sort concrete-function equals-pattern \
        fresh1 fresh2 imp-haskell imp-kore issue-101 issue-2273 issue-313 is-variable \
        matching-attribute no-dup-rules or-llvm or-ocaml poly-sort proj-attribute     \
        smt-prelude-attribute string_escape

SKIPPED_SUBDIRS=bytes bytes-ocaml float-id parser-hook set_unification

include ../../include/ktest-group.mak
